name: Deploy Hugo

on:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.161.1'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4